name: Build DuckDueller

on:
  # Manuel uniquement dans l’onglet Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Sécurité : vérifie l’intégrité du Gradle Wrapper
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      # Java 17
      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Cache Gradle performant
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build complet
      - name: Gradle Clean & Build
        run: ./gradlew --no-daemon clean build

      # Artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: duckdueller-build
          path: build/libs/*.jar
          if-no-files-found: error
